# Dhruv Bansal-101915061-ENC3 

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd

## About Dataset

The Banknote Dataset involves predicting whether a given banknote is authentic given a number of measures taken from a photograph.

It is a binary (2-class) classification problem.There are 1,372 observations with 4 input variables and 1 output variable. The variable names are as follows:

Variance of Wavelet Transformed image 

Skewness of Wavelet Transformed image 

Kurtosis of Wavelet Transformed image 

Entropy of image 

Output = 0 for authentic, 1 for inauthentic

the dataset has no catagorical data, no missing values.

## Importing the dataset

In [2]:
dataset = pd.read_csv('data_banknote_authentication.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40, random_state = 1)

In [4]:
print(X_train)

[[ 0.84546   3.4826   -3.6307   -1.3961  ]
 [ 1.105     7.4432    0.41099  -3.0332  ]
 [ 5.2012    0.32694   0.17965   1.1797  ]
 ...
 [-2.5919   -1.0553    3.8949    0.77757 ]
 [-1.3274    9.498     2.4408   -5.2689  ]
 [-0.11716   0.60422  -0.38587  -0.059065]]


In [5]:
print(y_train)

[1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1
 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1
 1 1 0 1 0 0 1 0 1 1 1 0 1 1 0 0 0 1 0 1 1 0 0 1 1 1 1 0 0 1 0 1 1 0 1 1 0
 0 1 0 1 0 0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 0 1 1 1 0
 0 0 0 0 1 0 0 1 1 0 1 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 1 0 1 1
 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1
 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 1
 0 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0
 1 1 1 0 1 1 0 1 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 0 1 0 1
 0 1 1 0 1 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 0
 1 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 0 0 1 1 0 1 1 0 1 0
 0 0 1 0 1 1 1 0 0 1 0 0 1 1 0 0 1 0 1 1 1 1 0 0 1 1 1 0 1 0 1 1 1 0 0 1 1
 0 0 0 1 1 0 1 1 1 1 0 1 

In [6]:
print(X_test)

[[ -4.3876   -7.7267   11.9655   -1.4543 ]
 [  1.4501    3.6067   -4.0557   -1.5966 ]
 [ -4.0173   -8.3123   12.4547   -1.4375 ]
 ...
 [ -0.24037  -1.7837    2.135     1.2418 ]
 [ -2.7611  -10.5099    9.0239   -1.9547 ]
 [  2.2034    5.9947    0.53009   0.84998]]


In [7]:
print(y_test)

[1 1 1 1 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1
 1 1 0 0 0 1 0 1 1 0 1 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0 1
 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 1 0 0
 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 0
 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 0
 0 0 1 1 1 0 1 1 0 1 1 0 0 1 1 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0
 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 0 1 0 1 1 0 0 1 1 1 1 1 0 1 1 1
 0 1 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0
 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 1
 0 0 0 1 1 1 1 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1
 0 0 1 1 0 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 0 1 0 1 1 0 1 0 1 1 1 0 0 1 1 1 1
 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 0 1 0 0 0 1 0 0 0
 0 1 1 1 0 1 0 0 1 1 1 0 

## Feature Scaling 

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
print(X_train)

[[ 0.15137339  0.24420079 -1.15721408 -0.08705409]
 [ 0.24308739  0.93695806 -0.1979713  -0.87578768]
 [ 1.69056708 -0.30776265 -0.25287685  1.15393301]
 ...
 [-1.06329113 -0.54953329  0.62888963  0.96019198]
 [-0.61645307  1.29636765  0.28377782 -1.952919  ]
 [-0.18878893 -0.25926299 -0.3870957   0.55711207]]


In [10]:
print(X_test)

[[-1.69784005 -1.71644255  2.54434203 -0.1150941 ]
 [ 0.36503584  0.2659074  -1.25808233 -0.18365239]
 [-1.56698664 -1.81887113  2.66044732 -0.10700007]
 ...
 [-0.23232782 -0.67693933  0.21120015  1.18385199]
 [-1.12308156 -2.20325818  1.84619136 -0.35618034]
 [ 0.63123047  0.68359773 -0.16970445  0.99507818]]


## Training the Decision Tree Classification model on the Training set

In [11]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Predicting the Test set results

In [12]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [0 0]]


## Making the Confusion Matrix

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[300   7]
 [  2 240]]


0.9836065573770492